#1
FROM node:12.16.1-alpine as build
WORKDIR /app

COPY package.json ./

RUN yarn install
COPY ./ ./
RUN yarn build
CMD ["yarn", "start"]

#2
FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html/
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
