FROM node:12.16.1-alpine as build
WORKDIR /app

COPY package.json ./

RUN yarn install
COPY ./ ./
# RUN yarn build
CMD ["yarn", "start"]

# FROM nginx:alpine
# COPY --from=build /app/dist/frontend /usr/share/nginx/html
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
