version: "3.9"

networks:
  local-dev:
    name: local-dev

services:
  frontend:
    container_name: react-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
    - local-dev

  backend:
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=QA;User=sa;Password=P@SSwordformssql;MultipleActiveResultSets=True;"
    ports:
      - "5000:80"
      - "5001:443"
    depends_on: 
      - mssql
    networks:
      - local-dev

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1434:1433"
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@SSwordformssql
    networks:
      - local-dev

